### ISSUE TITLE
Bonus round: Adicionar UF nos resultados.

### ISSUE THREAD

**Issue by marcosvpj** [ronanknob/datapirates_challenge#1]
Adicionar nos dados coletados a sigla do estado.

**Comment by ronanknob** [comment]
Sem problemas. Se vc olhar nos commits anteriores até existia essa informação. Vou recolocar assim que chegar em casa hoje e tiver acesso ao projeto.

**Comment by marcosvpj** [comment]
Outro ponto, ao invés dos dados virem em um array, poderia usar um objeto para poder nomear os campos.

**Comment by ronanknob** [comment]
@marcosvpj No último commit adicionei a UF como atributo. Criei o tipo de objeto FaixaCep e converti os registros. O arquivo output agora é um JSON com os campos nomeados.

**Comment by ronanknob** [comment]
@marcosvpj No último commit adicionei a UF como atributo. Criei o tipo de objeto FaixaCep e converti os registros. O arquivo output agora é um JSON com os campos nomeados. Isso encerra as pendências?
